project:
  type: website

website:
  title: "du-gartre"
  search: false
  page-footer: 
    left: "[Source](https://github.com/du-gartre/du-gartre.github.io)"  
    right: right: "Built with {{< iconify simple-icons:quarto >}} [Quarto](http://quarto.org)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



