---
title: "CV"
---

# Employment

-   **2021-2025** Data modeler, Health Research Consortium (CISIDAT) & Decision Analysis Under Uncertain Contexts Project (PADeCI).

-   2019  Policy consultant, Municipality of Aguascalientes.

-   2018  Parliamentary work assistant, Senate of the Mexican Republic.

-   2018  Research assistant, National Public Policy Laboratory (LNPP).

# Education

-   **2025-present**  Epidemiology, Ph.D., *University of Ottawa*, Ottawa, CA.

-   **2019-2021**  Methods for Public Policy Analysis, M.Sc., *Center for Research and Teaching in Economics (CIDE)*, Aguascalientes, MX.

-   **2013-2019**  Economics, B.A., *National Autonomous University of Mexico (UNAM)*, Mexico City, MX.

-   **2017**  International academic exchange, *Université Lumière Lyon II*, Lyon, FR.

# Teaching Experience

-   2025  Cost-Effectiveness and Decision Modeling using R workshop, Decision Analysis in R for Technologies in Health workgroup. Toronto, Canada.

-   **2021**  Applied Mathematics, T.A., *Center for Research and Teaching in Economics, graduate level.* Aguascalientes, Mexico.

# Awards and honors

-   **2025**  Scholarship for master and doctoral degrees in humanities and science in foreign countries (*Ministry of Science, Humanities, Technology and Innovation, Mexico*)
-   **2022**  Lee B. Lusted finalist, outstanding research (*Society for Medical Decision Making, 44th Annual North American Meeting*)
-   **2019-2021**  Graduate Fellowship for Masters Studies (*Ministry of Science, Humanities, Technology and Innovation, Mexico*)
-   **2019**  Graduated with honors, Bachelor of Economics (*Faculty of Economics, National Autonomous University of Mexico*)
-   **2017**  Academic exchange funding scholarship (*Foundation of the National Autonomous University of Mexico*)
-   **2014-2018**  Academic excellence scholarship (*Alumni Association, Faculty of Economics, National Autonomous University of Mexico*)

# Publications

-   **Garibay-Treviño, D. U.**, Jalal, H., & Alarid-Escudero, F. (2025). A Fast Nonparametric Sampling Method for Time to Event in Individual-Level Simulation Models. *Medical decision making : an international journal of the Society for Medical Decision Making*, 45(2), 205–213. <https://doi.org/10.1177/0272989X241308768>

# Languages

-   Spanish: Native level

-   English: CEFR level C2

-   French: DELF B2

# Skills

-   *Computing*:

    -   Most experienced: R, Python, Stata, Excel, LaTEX

    -   Some experience: Qualtrics, Stan.
